version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly-data:/data

volumes:
  redis-data:
    driver: local
  dragonfly-data:
    driver: local
