services:
  # simulation:
  #   build: ./simulation
  #   container_name: simulation
  #   ports:
  #     - "50051:50051"
  #     - "8080:8080"
  #   depends_on:
  #     dragonfly:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #     timescaledb:
  #       condition: service_healthy
  #   environment:
  #     REDIS_HOST: ${REDIS_HOST:-dragonfly}
  #     MINIO_HOST: ${MINIO_HOST:-minio}
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadminpassword}
  #     POSTGRES_HOST: ${POSTGRES_HOST:-timescaledb}
  #     POSTGRES_USER: ${POSTGRES_USER:-user}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     POSTGRES_DB: ${POSTGRES_DB:-db}
  #   volumes:
  #     - ./meshes:/app/meshes:ro
  #     - ./scenario:/app/scenario:rw
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #     restart_policy:
  #       condition: on-failure
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly-data:/data
    networks:
      simulation_network:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadminpassword}
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"
    networks:
      simulation_network:
        aliases:
          - object-store
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      simulation_network:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      timescaledb:
        condition: service_healthy
    dns:
      - 8.8.8.8
    networks:
      simulation_network:
        aliases:
          - monitoring

volumes:
  dragonfly-data:
    driver: local
  minio_data:
    driver: local
  minio_config:
    driver: local
  timescaledb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  simulation_network:
    driver: bridge
