site_name: "3D simulation to calculate the coefficients of friction between two objects using IPC and FEM"
site_url: "https://github.com/ETSTribology/ServerIPC"
site_description: "3D simulation to calculate the coefficients of friction between two objects"
site_author: "Antoine Boucher"

# Repository settings for edit links
repo_url: "https://github.com/ETSTribology/ServerIPC"
repo_name: "ETSTribology/ServerIPC"
edit_uri: "blob/main/docs"

# Theme configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
  favicon: "_static/imgs/favicon.ico"
  logo: "_static/imgs/pbat.svg"

# Navigation structure
nav:
  - Home: 
      - Overview: index.md
      - Installation: installation.md
        CUDA: cuda.md
      - Quickstart: quickstart.md
      - Gallery: gallery.md
  - Code Coverage: coverage.md
  - API:
      - Core:
          - Overview: "reference/core/index.md"
          - Contact: "reference/core/contact/index.md"
          - Math: "reference/core/math/index.md"
          - Materials: "reference/core/materials/index.md"
          - Registry: "reference/core/registry/index.md"
          - Solvers: "reference/core/solvers/index.md"
          - States: "reference/core/states/index.md"
          - Utils:
              - Overview: "reference/core/utils/index.md"
              - Config:
                - Overview: "reference/core/utils/config/index.md"
                - Schema: "reference/core/utils/config/schema.md"
              - IO: "reference/core/utils/io/index.md"
              - Logs: "reference/core/utils/logs/index.md"
              - Modifier: "reference/core/utils/modifier/index.md"
      - Simulation: "reference/simulation/index.md"
      - Network:
          - Overview: "reference/nets/index.md"
          - Controller: "reference/nets/controller/index.md"
          - Proto: "reference/nets/proto/index.md"
          - Serialization: "reference/nets/serialization/index.md"
          - Storage: "reference/nets/storage/index.md"
      - Visualization: "reference/visualization/index.md"
  - Courses:
    - FEM:
        - Introduction: course/fem/index.md
        - Method: course/fem/method.md
        - Shape Functions: course/fem/shape_functions.md
        - Spatial Integration: course/fem/spatial_integration.md
        - Operators: course/fem/operators.md
        - Boundary Conditions: course/fem/boundary_conditions.md
        - Vector-valued Functions: course/fem/vector_valued_functions.md
        - Limitations: course/fem/limitations.md
    - Math:
      - Introduction: course/math/index.md
      - Linear Algebra: course/math/linear_algebra.md
      - Optimization: course/math/optimization.md
  - Development:
    - Changelog: changelog.md
    - Contributing: contributing.md
    - Code of Conduct: code_of_conduct.md
    - License: license.md



# Markdown extensions and plugins
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - mkdocs_graphviz
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2:
      version: 11.4.0
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
  - bibtex:
      bib_file: "docs/refs.bib"
  - include-markdown
  - git-revision-date-localized:
      locale: "en"
  - mkdocs-jupyter

# Paths to static files (CSS, JS, images)
extra_css:
  - "_static/stylesheets/custom.css"

extra_javascript:
  - "_static/javascripts/config.js"
  - "_static/javascripts/custom.js"
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

# Static files to include
extra:
  css:
    - "_static/stylesheets/custom.css"
  js:
    - "_static/javascripts/custom.js"

use_directory_urls: true
strict: false
