# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "simulation.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10simulation.proto\x12\nsimulation"\x07\n\x05\x45mpty"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t"3\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t",\n\x0b\x44\x61taRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t"0\n\x0c\x44\x61taResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"!\n\x0e\x43ommandMessage\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t2\xe3\x01\n\x11SimulationService\x12\x46\n\x0bSendCommand\x12\x1a.simulation.CommandRequest\x1a\x1b.simulation.CommandResponse\x12@\n\x0bPublishData\x12\x17.simulation.DataRequest\x1a\x18.simulation.DataResponse\x12\x44\n\x11SubscribeCommands\x12\x11.simulation.Empty\x1a\x1a.simulation.CommandMessage0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "simulation_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EMPTY"]._serialized_start = 32
    _globals["_EMPTY"]._serialized_end = 39
    _globals["_COMMANDREQUEST"]._serialized_start = 41
    _globals["_COMMANDREQUEST"]._serialized_end = 74
    _globals["_COMMANDRESPONSE"]._serialized_start = 76
    _globals["_COMMANDRESPONSE"]._serialized_end = 127
    _globals["_DATAREQUEST"]._serialized_start = 129
    _globals["_DATAREQUEST"]._serialized_end = 173
    _globals["_DATARESPONSE"]._serialized_start = 175
    _globals["_DATARESPONSE"]._serialized_end = 223
    _globals["_COMMANDMESSAGE"]._serialized_start = 225
    _globals["_COMMANDMESSAGE"]._serialized_end = 258
    _globals["_SIMULATIONSERVICE"]._serialized_start = 261
    _globals["_SIMULATIONSERVICE"]._serialized_end = 488
# @@protoc_insertion_point(module_scope)
