# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import simulation.nets.live.proto.simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = "1.68.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in simulation_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SimulationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.SendCommand = channel.unary_unary(
            "/simulation.SimulationService/SendCommand",
            request_serializer=simulation__pb2.CommandRequest.SerializeToString,
            response_deserializer=simulation__pb2.CommandResponse.FromString,
            _registered_method=True,
        )
        self.PublishData = channel.unary_unary(
            "/simulation.SimulationService/PublishData",
            request_serializer=simulation__pb2.DataRequest.SerializeToString,
            response_deserializer=simulation__pb2.DataResponse.FromString,
            _registered_method=True,
        )
        self.SubscribeCommands = channel.unary_stream(
            "/simulation.SimulationService/SubscribeCommands",
            request_serializer=simulation__pb2.Empty.SerializeToString,
            response_deserializer=simulation__pb2.CommandMessage.FromString,
            _registered_method=True,
        )


class SimulationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PublishData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubscribeCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendCommand": grpc.unary_unary_rpc_method_handler(
            servicer.SendCommand,
            request_deserializer=simulation__pb2.CommandRequest.FromString,
            response_serializer=simulation__pb2.CommandResponse.SerializeToString,
        ),
        "PublishData": grpc.unary_unary_rpc_method_handler(
            servicer.PublishData,
            request_deserializer=simulation__pb2.DataRequest.FromString,
            response_serializer=simulation__pb2.DataResponse.SerializeToString,
        ),
        "SubscribeCommands": grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeCommands,
            request_deserializer=simulation__pb2.Empty.FromString,
            response_serializer=simulation__pb2.CommandMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "simulation.SimulationService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "simulation.SimulationService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCommand(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/simulation.SimulationService/SendCommand",
            simulation__pb2.CommandRequest.SerializeToString,
            simulation__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PublishData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/simulation.SimulationService/PublishData",
            simulation__pb2.DataRequest.SerializeToString,
            simulation__pb2.DataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubscribeCommands(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/simulation.SimulationService/SubscribeCommands",
            simulation__pb2.Empty.SerializeToString,
            simulation__pb2.CommandMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
